# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.anchor_color", "#0000FF");
user_pref("browser.cache.disk.capacity", 50000);
user_pref("browser.download.dir", "~");
user_pref("browser.visited_color", "#FF0000");
user_pref("capability.policy.default.checkloaduri.enabled", "noAccess");
user_pref("capability.policy.myportalok.checkloaduri.enabled", "allAccess");
user_pref("capability.policy.myportalok.sites", "myportal:");
user_pref("capability.policy.policynames", "myportalok");
user_pref("font.default", "serif");
user_pref("intl.accept_languages", "en");
user_pref("intl.charset.default", "ISO-8859-1");
user_pref("intl.charset.detector", "");
user_pref("network.image.imageBehavior", 0);
user_pref("network.proxy.http_port", 8080);
user_pref("network.proxy.no_proxies_on", "localhost, 127.0.0.0/8");
